---
# Set to 'pi' for Raspberry Pi OS, or 'pirate' for HypriotOS.
ansible_user: pirate
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"

# Set to 'arm64' for a 64-bit OS, or 'arm' for 32-bit.
helm_arch: arm

# Chart versions
booksonic_chart_version: 0.1.4
diun_chart_version: 0.1.2
gotify_chart_version: 0.1.8
homebridge_chart_version: 1.0.2
installer_chart_version: 0.1.9
papermerge_chart_version: 0.1.2
pihole_chart_version: 1.7.20
transmission_chart_version: 0.1.10

# Turing Pi.
ingress_server_ip: ""
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: "America/Los_Angeles"

# NFS
nfs_server_ip: 192.168.1.192
storage_class: "managed-nfs-storage"
