---
- name: Get the ingress ip address
  block:
    - name: Get the traefik service
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        name: traefik
        namespace: kube-system
      register: traefik

    - name: Set the ingress ip fact
      set_fact:
        ingress_server_ip: "{{ traefik['resources'][0]['status']['loadBalancer']['ingress'][0]['ip'] }}"
  when: (ingress_server_ip is not defined) or (ingress_server_ip|length == 0)
