---
- name: Create papermerge namespace.
  k8s:
    name: papermerge
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy papermerge Helm chart.
  kubernetes.core.helm:
    name: papermerge
    chart_ref: nicholaswilde/papermerge
    chart_version: '{{ papermerge_chart_version }}'
    release_namespace: papermerge
    update_repo_cache: yes
    state: present
    values:
      config:
        TZ: "{{ timezone }}"
      persistence:
        config:
          enabled: true
          storageClass: "{{ storage_class }}"
        data:
          enabled: true
          storageClass: "{{ storage_class }}"
      ingress:
        enabled: true
        hosts:
          - host: "papermerge.{{ ingress_server_ip }}.nip.io"
            paths:
              - path: "/"
                pathType: Prefix
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
